import { Ticket_Type, Ticket_Priority} from '@/types/ticket';

export const DB = [
  {
    id: 1,
    title: "Onboarding email not delivered",
    description: "Users report signup email not arriving.",
    status: "OPEN",
    priority: Ticket_Priority.HIGH,

    type: Ticket_Type.BUG,
    createdAt: "2025-10-01T09:12:00Z",
    updatedAt: "2025-10-02T10:00:00Z",
    createdById: 2,
    assignedToId: 1,
    clientId: null,
    dueDate: "2025-10-10",
    tags: ["email","auth"],
  },
  {
    id: 2,
    title: "Mobile nav redesign",
    description: "Redesign mobile navigation for better reachability.",
    status: "UPCOMING",
    priority: Ticket_Priority.MEDIUM,
    type: "FEATURE_REQUEST",
    createdAt: "2025-09-20T12:00:00Z",
    updatedAt: "2025-09-20T12:00:00Z",
    createdById: 1,
    assignedToId: null,
    clientId: null,
    dueDate: "2025-11-01",
    tags: ["ui","mobile"],
  },
  {
    id: 3,
    title: "Payment retry bug",
    description: "Retry logic fails when network interrupts.",
    status: "IN_PROGRESS",
    priority: Ticket_Priority.URGENT,
    type: Ticket_Type.BUG,
    createdAt: "2025-09-25T15:22:00Z",
    updatedAt: "2025-10-03T08:40:00Z",
    createdById: 4,
    assignedToId: 3,
    clientId: 5,
    dueDate: "2025-10-05",
    tags: ["payments"],
  },
  {
    id: 4,
    title: "Invoice export CSV",
    description: "Add CSV export for invoices in reports.",
    status: "RESOLVED",
    priority: Ticket_Priority.LOW,
    type: Ticket_Type.GENERAL,
    createdAt: "2025-08-10T10:00:00Z",
    updatedAt: "2025-09-01T09:30:00Z",
    createdById: 2,
    assignedToId: 6,
    clientId: null,
    tags: ["export"],
  },
  {
    id: 5,
    title: "Slack integration: channel selection",
    description: "Allow selecting Slack channel per workspace for notifications.",
    status: "OPEN",
    priority: Ticket_Priority.MEDIUM,
    type: Ticket_Type.SUPPORT,
    createdAt: "2025-10-03T11:01:00Z",
    updatedAt: "2025-10-03T11:01:00Z",
    createdById: 1,
    assignedToId: null,
    tags: ["integration","slack"],
  },
  {
    id: 6,
    title: "Event reminder cron",
    description: "Scheduled job to remind attendees 24 hours before event.",
    status: "UPCOMING",
    priority: Ticket_Priority.LOW,
    type: Ticket_Type.EVENT,
    createdAt: "2025-09-28T09:00:00Z",
    updatedAt: "2025-09-28T09:00:00Z",
    createdById: 1,
    assignedToId: 2,
    tags: ["events","cron"],
  },
  {
    id: 7,
    title: "Remove legacy A/B flags",
    description: "Remove experiment flags from codebase.",
    status: "CANCELLED",
    priority: Ticket_Priority.LOW,
    type: Ticket_Type.GENERAL,
    createdAt: "2025-06-01T09:00:00Z",
    updatedAt: "2025-07-01T09:00:00Z",
    createdById: 3,
    assignedToId: null,
    tags: ["techdebt"],
  },
  {
    id: 8,
    title: "Improve search fuzziness",
    description: "Make global ticket search tolerant to typos.",
    status: "IN_PROGRESS",
    priority: Ticket_Priority.MEDIUM,
    type: "FEATURE_REQUEST",
    createdAt: "2025-09-18T09:00:00Z",
    updatedAt: "2025-10-05T12:30:00Z",
    createdById: 2,
    assignedToId: 1,
    tags: ["search","ux"],
  },
  {
    id: 9,
    title: "Billing address validation",
    description: "Add server-side validation for billing addresses.",
    status: "OPEN",
    priority: Ticket_Priority.HIGH,

    type: Ticket_Type.BUG,
    createdAt: "2025-10-05T14:00:00Z",
    updatedAt: "2025-10-05T14:00:00Z",
    createdById: 5,
    assignedToId: null,
    tags: ["billing"],
  },
  {
    id: 10,
    title: "Refactor ticket history model",
    description: "Split history by event types for easier querying.",
    status: "RESOLVED",
    priority: Ticket_Priority.MEDIUM,
    type: Ticket_Type.GENERAL,
    createdAt: "2025-08-25T08:00:00Z",
    updatedAt: "2025-09-10T09:00:00Z",
    createdById: 3,
    assignedToId: 2,
    tags: ["backend","refactor"],
  },
  {
    id: 11,
    title: "TicTask Dashboard",
    description: "Start building out TicTask Dashboard with user view.",
    status: "CLOSED",
    priority: Ticket_Priority.HIGH,

    type: Ticket_Type.GENERAL,
    createdAt: "2025-08-25T08:00:00Z",
    updatedAt: "2025-09-10T09:00:00Z",
    createdById: 3,
    assignedToId: 2,
    tags: ["frontend","design"],
  },
];